# Generated by Django 3.1.1 on 2020-12-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(blank=True, max_length=155)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=155)),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.product')),
                ('variant', models.ManyToManyField(to='agents.ProductAttribute')),
            ],
        ),
    ]
