# Generated by Django 3.1.1 on 2020-12-13 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_product_productattribute_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ManyToManyField(blank=True, related_name='product_color', to='agents.Product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.product')),
            ],
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant',
            field=models.ManyToManyField(blank=True, related_name='productvariant', to='agents.ProductAttribute'),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.product')),
                ('size', models.ManyToManyField(blank=True, related_name='productsize', to='agents.ProductColor')),
            ],
        ),
    ]
