# Generated by Django 3.1.1 on 2020-12-14 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_auto_20201214_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='variant',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductAttribute',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
