# Generated by Django 3.1.4 on 2021-01-05 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201214_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant',
            field=models.CharField(choices=[('None', 'None'), ('Size-Color', 'Size-Color')], default='None', max_length=10),
        ),
    ]
