# Generated by Django 3.1.4 on 2020-12-27 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_auto_20201214_1708'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.customer'),
        ),
    ]
