# Generated by Django 3.1.4 on 2021-01-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='adminnote',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='amount',
            new_name='total_amount',
        ),
    ]
